# 一个workflow，名为deploy to tengxunyun
name: deploy to tengxunyun

on: # 此CI/CD触发时的事件
  push: # 在代码提交时自动触发
    branches:
      - main
  workflow_dispatch:
# 一个 CI/CD 的工作流有许多 jobs 组成，比如最典型的 job 是 lint，test，build。
jobs: 
  build: # 构建job
    runs-on: ubuntu-latest # 跑workflow的服务器系统
    steps: # job的一系列动作
      - uses: actions/checkout@v3
      - name: Get the content of algolia.json as config
        id: algolia_config
        run: echo "config=$(cat crawlerConfig.json | jq -r tostring)" >> $GITHUB_OUTPUT
      - name: Push indices to Algolia
        uses: signcl/docsearch-scraper-action@master
        env:
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          API_KEY: ${{ secrets.API_KEY }}
          CONFIG: ${{ steps.algolia_config.outputs.config }}
        # 用于生成项目结构svg的job
      - name: Repo Visualizer
        uses: githubocto/repo-visualizer@0.8.2
        with:
          excluded_paths: "dist,node_modules"
          branch: main
      - name: use Node.js 16
        uses: actions/setup-node@master
        with:
          node-version: 16
      # 运行命令，npm install && npm run build
      - name: npm install and build
        run: |
          npm install
          npm run docs:build
        env:
          CI: true
      # 部署到腾讯云服务器
      - name: Deploy to Server
        uses: burnett01/rsync-deployments@5.2.1
        with:
            # 本地.ssh文件下的私钥id_rsa，存在secrets的TOKEN中
            switches: -avzr --delete
            path: website/
            remote_path: /opt/web/website/
            remote_host: ${{ secrets.HOST }} 
            remote_user: ${{ secrets.USER }} 
            remote_key: ${{ secrets.TOKEN }} 
